version: '3'

services:
  db:
    image: mongo:5.0.0
    container_name: pokedex-database
    restart : always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongoData/db:/data/db
      - ./mongoData/configdb:/data/configdb
